### ISSUE TITLE
Implement sound

### ISSUE THREAD

**Issue by Elizafox** [supergameherm/supergameherm#16]
Definitely need to do this. SDL already has some bits in its frontend for this. Right now we have a lot of bits to write to the sound regs, but nothing else.

**Comment by iamgreaser** [comment]
Work started on this. Currently everything pertaining to actual playback is in the SDL frontend and I'm not aiming to make it very accurate right now. If you can somehow shift it to the core we'll have something useful... but with that said, NR3x and NR4x need implementing.

**Comment by Elizafox** [comment]
Very nice, needs more improvement, but it's getting there! Good work @iamgreaser
