### ISSUE TITLE
jumalauta's skinke demo doesn't animate properly

### ISSUE THREAD

**Issue by iamgreaser** [supergameherm/supergameherm#21]
This may be releated to #15 and will probably be solved by solving #15 but whatever.
ROM: http://gameboy.modermodemet.se/en/demo/147

**Comment by Elizafox** [comment]
Possibly related to #12

**Comment by Elizafox** [comment]
This HAS to be vblank related... I disassembled the ROM: http://i.imgur.com/29YU8xc.png - I am positive the vblank timings are wrong now.

**Comment by Elizafox** [comment]
Possible duplicate of #22

**Comment by iamgreaser** [comment]
This was NOT a duplicate. It was due to the demo abusing SB (serial in/out data) as a scratch register.

This has been fixed in c11c337 and now has a separate problem to be solved.
