### ISSUE TITLE
Build fails on Mac OS X due to MAP_ANONYMOUS not existing

### ISSUE THREAD

**Issue by awilfox** [supergameherm/supergameherm#25]
We may need a CMake check for MAP_ANONYMOUS (Linux, newer FreeBSD) vs MAP_ANON (Mac OS X 10.0 through at least 10.8, older FreeBSD) to ensure we can successfully build on Mac OS X.

**Comment by Elizafox** [comment]
Could you check if MAP_ANON exists?

**Comment by awilfox** [comment]
Yes, MAP_ANON exists on all versions of Mac OS X, but the build then fails for other reasons on Mac OS X - the same reason VS 2005 and 2008 can't build it.  "Redefinition of typedef memmap_state: previous definition was in typedefs.h".

**Comment by iamgreaser** [comment]
FreeBSD mmap(2) man page:

     MAP_ANON           Map anonymous memory not associated with any specific
                        file.  The file descriptor used for creating MAP_ANON
                        must be -1.  The offset argument must be 0.

     MAP_ANONYMOUS      This flag is identical to MAP_ANON and is provided for
                        compatibility.

Linux mmap man page (ripped from about.com):

    MAP_ANONYMOUS
        The mapping is not backed by any file; the fd and offset arguments are ignored. This flag in conjunction with MAP_SHARED is implemented since Linux 2.4. 
    MAP_ANON
        Alias for MAP_ANONYMOUS. Deprecated. 

I'd say we favour MAP_ANON over MAP_ANONYMOUS, considering that Linux has support for the former name since at least 2.4.2, and I seriously doubt they'd drop the alias (cue Linus screaming "YOU DON'T FUCKING BREAK USERSPACE").

**Comment by Elizafox** [comment]
I just define MAP_ANONYMOUS as MAP_ANON's value if MAP_ANONYMOUS isn't defined, because it was the path of least resistance. It would be trivial to do the obverse.
